from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def _fmt(value: Any, decimals: int = 3) -> str:
    if isinstance(value, float):
        return f"{value:.{decimals}f}"
    if value is None:
        return "—"
    return str(value)


def _quality_table(quality: dict[str, Any]) -> str:
    checks = quality.get("checks", [])
    if not checks:
        return "_No checks recorded._\n"
    rows = ["| Check | Value | Status |", "|---|---|---|"]
    for c in checks:
        status = "PASS" if c.get("passed") else "FAIL"
        rows.append(f"| {c['check']} | {c['value']} | {status} |")
    return "\n".join(rows) + "\n"


def _freshness_block(freshness: dict[str, Any]) -> str:
    is_fresh = freshness.get("is_fresh", False)
    status = "Fresh" if is_fresh else "Stale"
    return (
        f"- **Status**: {status}\n"
        f"- Latest published: `{freshness.get('latest_published', '—')}`\n"
        f"- Oldest published: `{freshness.get('oldest_published', '—')}`\n"
        f"- Stale rows: {freshness.get('stale_rows', '—')} / {freshness.get('total_rows', '—')} "
        f"(threshold: {freshness.get('freshness_threshold_days', '—')} days)\n"
    )


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    lines: list[str] = []

    lines.append("# Phase 1 — Baseline Report\n")

    # Source summary
    lines.append("## 1. Data Source\n")
    for k, v in source_summary.items():
        lines.append(f"- **{k}**: {v}")
    lines.append("")

    # Metrics
    lines.append("## 2. Evaluation Metrics\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    for key in ("samples", "retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"):
        if key in metrics:
            lines.append(f"| {key} | {_fmt(metrics[key])} |")
    lines.append("")

    ragas = metrics.get("ragas", {})
    if ragas and not ragas.get("skipped") and not ragas.get("error"):
        lines.append("### RAGAS Metrics\n")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        for k, v in ragas.items():
            lines.append(f"| {k} | {_fmt(v)} |")
        lines.append("")

    # Data quality
    lines.append("## 3. Data Quality\n")
    passed = quality.get("checks_passed", "—")
    total = quality.get("checks_total", "—")
    all_ok = quality.get("all_passed", False)
    lines.append(f"**Result**: {passed}/{total} checks passed — {'ALL PASS' if all_ok else 'SOME FAILED'}\n")
    lines.append(_quality_table(quality))

    # Freshness
    lines.append("## 4. Freshness\n")
    lines.append(_freshness_block(freshness))
    lines.append("")

    lines.append("---")
    lines.append("_Generated by data pipeline observability module._\n")

    write_text(Path(report_path), "\n".join(lines))


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    lines: list[str] = []

    lines.append("# Corruption Impact Report — Baseline / Corrupted / Repaired\n")

    # Executive summary
    b_hr = baseline_metrics.get("retrieval_hit_rate", 0)
    c_hr = corrupted_metrics.get("retrieval_hit_rate", 0)
    r_hr = repaired_metrics.get("retrieval_hit_rate", 0)
    delta_corrupt = round((c_hr - b_hr) * 100, 1)
    delta_repair = round((r_hr - b_hr) * 100, 1)
    lines.append("## 1. Executive Summary\n")
    lines.append(
        f"Data corruption changed `retrieval_hit_rate` by **{delta_corrupt:+.1f}%** vs baseline. "
        f"After repair the delta is **{delta_repair:+.1f}%** vs baseline.\n"
    )

    # Metric comparison table
    lines.append("## 2. Metric Comparison\n")
    metric_keys = ["samples", "retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"]
    lines.append("| Metric | Baseline | Corrupted | Repaired |")
    lines.append("|---|---|---|---|")
    for key in metric_keys:
        b = _fmt(baseline_metrics.get(key))
        c = _fmt(corrupted_metrics.get(key))
        r = _fmt(repaired_metrics.get(key))
        lines.append(f"| {key} | {b} | {c} | {r} |")
    lines.append("")

    # Quality comparison
    lines.append("## 3. Data Quality — Corrupted vs Repaired\n")
    c_checks = {ch["check"]: ch for ch in corrupted_quality.get("checks", [])}
    r_checks = {ch["check"]: ch for ch in repaired_quality.get("checks", [])}
    all_check_names = sorted(set(c_checks) | set(r_checks))
    lines.append("| Check | Corrupted | Repaired |")
    lines.append("|---|---|---|")
    for name in all_check_names:
        c_status = "PASS" if c_checks.get(name, {}).get("passed") else "FAIL"
        r_status = "PASS" if r_checks.get(name, {}).get("passed") else "FAIL"
        lines.append(f"| {name} | {c_status} | {r_status} |")
    lines.append("")

    # Freshness comparison
    lines.append("## 4. Freshness — Corrupted vs Repaired\n")
    lines.append("### Corrupted\n")
    lines.append(_freshness_block(corrupted_freshness))
    lines.append("### Repaired\n")
    lines.append(_freshness_block(repaired_freshness))
    lines.append("")

    # Root cause analysis
    lines.append("## 5. Root Cause Analysis\n")
    lines.append(
        "| Corruption type | Signal | Impact on RAG |\n"
        "|---|---|---|\n"
        "| Blank summary | `summary_not_blank` FAIL | Embedding mất ngữ nghĩa → retrieval miss |\n"
        "| Noise injection | `mean_token_f1` giảm | Câu trả lời sai dù retrieve đúng doc |\n"
        "| Drop latest records | `retrieval_hit_rate` giảm | Paper trong test set không còn trong index |\n"
        "| Stale dates | `is_fresh` = False | Freshness gate cảnh báo, dữ liệu lỗi thời |\n"
        "| Duplicate rows | `paper_id_unique` FAIL | Index bị pha loãng, precision giảm |\n"
        "| Truncated title | exact lookup miss | Agent không tìm được paper theo tên |\n"
    )
    lines.append("")

    lines.append("## 6. Conclusion\n")
    lines.append(
        "Mọi loại corruption đều có tác động đo được lên metric. "
        "Pipeline cần chạy quality + freshness gate **trước** khi rebuild index "
        "để tránh phục vụ câu trả lời sai cho người dùng. "
        "Repair từ raw data đã khôi phục performance về gần baseline.\n"
    )

    lines.append("---")
    lines.append("_Generated by data pipeline observability module._\n")

    write_text(Path(report_path), "\n".join(lines))
