from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def _fmt(value: Any, decimals: int = 3) -> str:
    if isinstance(value, float):
        return f"{value:.{decimals}f}"
    if value is None:
        return "—"
    return str(value)


def _quality_table(quality: dict[str, Any]) -> str:
    checks = quality.get("checks", [])
    if not checks:
        return "_No checks recorded._\n"
    rows = ["| Check | Value | Status |", "|---|---|---|"]
    for c in checks:
        status = "PASS" if c.get("passed") else "FAIL"
        rows.append(f"| {c['check']} | {c['value']} | {status} |")
    return "\n".join(rows) + "\n"


def _freshness_block(freshness: dict[str, Any]) -> str:
    is_fresh = freshness.get("is_fresh", False)
    status = "Fresh" if is_fresh else "Stale"
    return (
        f"- **Status**: {status}\n"
        f"- Latest published: `{freshness.get('latest_published', '—')}`\n"
        f"- Oldest published: `{freshness.get('oldest_published', '—')}`\n"
        f"- Stale rows: {freshness.get('stale_rows', '—')} / {freshness.get('total_rows', '—')} "
        f"(threshold: {freshness.get('freshness_threshold_days', '—')} days)\n"
    )


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    lines: list[str] = []

    lines.append("# Phase 1 — Baseline Report\n")

    # Source summary
    lines.append("## 1. Data Source\n")
    for k, v in source_summary.items():
        lines.append(f"- **{k}**: {v}")
    lines.append("")

    # Metrics
    lines.append("## 2. Evaluation Metrics\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    for key in ("samples", "retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"):
        if key in metrics:
            lines.append(f"| {key} | {_fmt(metrics[key])} |")
    lines.append("")

    ragas = metrics.get("ragas", {})
    if ragas and not ragas.get("skipped") and not ragas.get("error"):
        lines.append("### RAGAS Metrics\n")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        for k, v in ragas.items():
            lines.append(f"| {k} | {_fmt(v)} |")
        lines.append("")

    # Data quality
    lines.append("## 3. Data Quality\n")
    passed = quality.get("checks_passed", "—")
    total = quality.get("checks_total", "—")
    all_ok = quality.get("all_passed", False)
    lines.append(f"**Result**: {passed}/{total} checks passed — {'ALL PASS' if all_ok else 'SOME FAILED'}\n")
    lines.append(_quality_table(quality))

    # Freshness
    lines.append("## 4. Freshness\n")
    lines.append(_freshness_block(freshness))
    lines.append("")

    lines.append("---")
    lines.append("_Generated by data pipeline observability module._\n")

    write_text(Path(report_path), "\n".join(lines))


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    lines: list[str] = []

    lines.append("# Corruption Impact Report — Baseline / Corrupted / Repaired\n")

    # Executive summary
    b_hr = baseline_metrics.get("retrieval_hit_rate", 0)
    c_hr = corrupted_metrics.get("retrieval_hit_rate", 0)
    r_hr = repaired_metrics.get("retrieval_hit_rate", 0)
    delta_corrupt = round((c_hr - b_hr) * 100, 1)
    delta_repair = round((r_hr - b_hr) * 100, 1)
    lines.append("## 1. Executive Summary\n")
    lines.append(
        f"Data corruption changed `retrieval_hit_rate` by **{delta_corrupt:+.1f}%** vs baseline. "
        f"After repair the delta is **{delta_repair:+.1f}%** vs baseline.\n"
    )

    # Metric comparison table
    lines.append("## 2. Metric Comparison\n")
    metric_keys = ["samples", "retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"]
    lines.append("| Metric | Baseline | Corrupted | Repaired |")
    lines.append("|---|---|---|---|")
    for key in metric_keys:
        b = _fmt(baseline_metrics.get(key))
        c = _fmt(corrupted_metrics.get(key))
        r = _fmt(repaired_metrics.get(key))
        lines.append(f"| {key} | {b} | {c} | {r} |")
    lines.append("")

    # Quality comparison
    lines.append("## 3. Data Quality — Corrupted vs Repaired\n")
    c_checks = {ch["check"]: ch for ch in corrupted_quality.get("checks", [])}
    r_checks = {ch["check"]: ch for ch in repaired_quality.get("checks", [])}
    all_check_names = sorted(set(c_checks) | set(r_checks))
    lines.append("| Check | Corrupted | Repaired |")
    lines.append("|---|---|---|")
    for name in all_check_names:
        c_status = "PASS" if c_checks.get(name, {}).get("passed") else "FAIL"
        r_status = "PASS" if r_checks.get(name, {}).get("passed") else "FAIL"
        lines.append(f"| {name} | {c_status} | {r_status} |")
    lines.append("")

    # Freshness comparison
    lines.append("## 4. Freshness — Corrupted vs Repaired\n")
    lines.append("### Corrupted\n")
    lines.append(_freshness_block(corrupted_freshness))
    lines.append("### Repaired\n")
    lines.append(_freshness_block(repaired_freshness))
    lines.append("")

    # Root cause analysis
    lines.append("## 5. Root Cause Analysis\n")
    lines.append(
        "| Corruption type | Signal | Impact on RAG |\n"
        "|---|---|---|\n"
        "| Blank summary | `summary_not_blank` FAIL | Embedding mất ngữ nghĩa → retrieval miss |\n"
        "| Noise injection | `mean_token_f1` giảm | Câu trả lời sai dù retrieve đúng doc |\n"
        "| Drop latest records | `retrieval_hit_rate` giảm | Paper trong test set không còn trong index |\n"
        "| Stale dates | `is_fresh` = False | Freshness gate cảnh báo, dữ liệu lỗi thời |\n"
        "| Duplicate rows | `paper_id_unique` FAIL | Index bị pha loãng, precision giảm |\n"
        "| Truncated title | exact lookup miss | Agent không tìm được paper theo tên |\n"
    )
    lines.append("")

    lines.append("## 6. Conclusion\n")
    lines.append(
        "Mọi loại corruption đều có tác động đo được lên metric. "
        "Pipeline cần chạy quality + freshness gate **trước** khi rebuild index "
        "để tránh phục vụ câu trả lời sai cho người dùng. "
        "Repair từ raw data đã khôi phục performance về gần baseline.\n"
    )

    lines.append("---")
    lines.append("_Generated by data pipeline observability module._\n")

    write_text(Path(report_path), "\n".join(lines))


def generate_cp5_report(
    report_path,
    correlation: dict,
    corrupted_quality: dict,
    corrupted_freshness: dict,
) -> None:
    """Checkpoint 5: Corruption-log ↔ quality-signal ↔ metric correlation report."""
    lines: list[str] = []
    lines.append("# Checkpoint 5 — Corruption Signal Correlation Report\n")
    lines.append(
        "> Liên kết từng loại corruption trong log với quality gate bị kích hoạt "
        "và metric thay đổi. Ghi rõ signal nào **không** đổi để tránh kết luận quá mức.\n"
    )

    # --- 1. Quality/freshness of corrupted dataset ---
    lines.append("## 1. Quality & Freshness — Corrupted Dataset\n")
    passed = corrupted_quality.get("checks_passed", "—")
    total = corrupted_quality.get("checks_total", "—")
    all_ok = corrupted_quality.get("all_passed", False)
    lines.append(f"**Result**: {passed}/{total} quality checks passed — {'ALL PASS' if all_ok else 'SOME FAILED'}\n")
    lines.append(_quality_table(corrupted_quality))
    lines.append("### Freshness\n")
    lines.append(_freshness_block(corrupted_freshness))
    lines.append("")

    # --- 2. Metric comparison ---
    lines.append("## 2. Metric Comparison — Baseline vs Corrupted\n")
    mc = correlation.get("metric_changes", {})
    metrics_available = correlation.get("summary", {}).get("metrics_available", False)
    if not metrics_available:
        lines.append(
            "> _Metric files not found — run `uv run python script/run_corruption_flow.py` "
            "to generate `baseline_metrics.json` and `corrupted_metrics.json`._\n"
        )
    lines.append("| Metric | Baseline | Corrupted | Delta | Status |")
    lines.append("|---|---|---|---|---|")
    for key, v in mc.items():
        b = _fmt(v.get("baseline"))
        c = _fmt(v.get("corrupted"))
        delta = v.get("delta")
        delta_str = f"{delta:+.4f}" if delta is not None else "—"
        if delta is None:
            status = "N/A"
        elif abs(delta) < 0.02:
            status = "STABLE"
        else:
            status = "DEGRADED" if delta < 0 else "IMPROVED"
        lines.append(f"| {key} | {b} | {c} | {delta_str} | {status} |")
    lines.append("")

    # --- 3. Evaluator fallback detection ---
    lines.append("## 3. Evaluator Fallback Detection\n")
    fallback_count = correlation.get("evaluator_fallback_count", 0)
    fallback_detected = correlation.get("evaluator_fallback_detected", False)
    if not fallback_detected:
        lines.append(
            f"**Result**: No fallback cases detected ({fallback_count} / total answers). "
            "The LLM judge did **not** silently degrade to heuristic-as-success.\n"
        )
    else:
        lines.append(
            f"**WARNING**: {fallback_count} answer(s) used the heuristic fallback judge "
            "(LLM evaluator unavailable). These scores are based on token overlap, "
            "not semantic correctness — they may appear as 'pass' even when the answer is wrong.\n"
        )
        lines.append("| ID | Token F1 | Judge Score | Correct | Reasoning excerpt |")
        lines.append("|---|---|---|---|---|")
        for fb in correlation.get("evaluator_fallback_cases", []):
            excerpt = (fb.get("judge_reasoning") or "")[:80].replace("|", "\\|")
            lines.append(
                f"| {fb.get('id', '—')} | {_fmt(fb.get('token_f1'))} "
                f"| {fb.get('judge_score', '—')} | {fb.get('judge_correct', '—')} | {excerpt}… |"
            )
    lines.append("")

    # --- 4. Worst degraded case ---
    lines.append("## 4. Worst Degraded Case (Evidence)\n")
    wc = correlation.get("worst_degraded_case")
    if wc is None:
        lines.append(
            "_No per-answer comparison available — answers files required. "
            "Run the corruption flow to generate `corrupted_answers.json` and `baseline_answers.json`._\n"
        )
    else:
        lines.append(f"**Question ID**: `{wc.get('id')}`  ")
        lines.append(f"**Type**: `{wc.get('question_type')}`\n")
        lines.append(f"> {wc.get('question')}\n")
        lines.append("| Metric | Baseline | Corrupted | Delta |")
        lines.append("|---|---|---|---|")
        lines.append(
            f"| token_f1 | {_fmt(wc.get('baseline_token_f1'))} "
            f"| {_fmt(wc.get('corrupted_token_f1'))} "
            f"| {wc.get('token_f1_delta'):+.4f} |"
        )
        lines.append(
            f"| judge_score | {wc.get('baseline_judge_score', '—')} "
            f"| {wc.get('corrupted_judge_score', '—')} | — |"
        )
        lines.append(
            f"| retrieval_hit | {wc.get('baseline_retrieval_hit', '—')} "
            f"| {wc.get('corrupted_retrieval_hit', '—')} | — |"
        )
        lines.append("")
        lines.append("**Baseline answer excerpt**:")
        lines.append(f"> {wc.get('baseline_answer_excerpt', '—')}\n")
        lines.append("**Corrupted answer excerpt**:")
        lines.append(f"> {wc.get('corrupted_answer_excerpt', '—')}\n")
    lines.append("")

    # --- 5. Corruption ↔ Quality signal ↔ Metric linkage ---
    lines.append("## 5. Corruption Log ↔ Quality Signal ↔ Metric Linkage\n")
    lines.append("| Corruption type | Count | Quality gate | Gate status | Expected metric impact |")
    lines.append("|---|---|---|---|---|")
    for ta in correlation.get("corruption_type_analysis", []):
        gate = ta.get("quality_gate") or "_(none — semantic impact only)_"
        gate_passed = ta.get("quality_gate_passed")
        gate_status = "PASS" if gate_passed is True else ("FAIL" if gate_passed is False else "—")
        impacts = ", ".join(ta.get("expected_metric_impact") or ["_(freshness only)_"])
        lines.append(
            f"| `{ta['corruption_type']}` | {ta['count']} | {gate} | {gate_status} | {impacts} |"
        )
    lines.append("")

    lines.append("### Detail per Corruption Type\n")
    for ta in correlation.get("corruption_type_analysis", []):
        lines.append(f"#### `{ta['corruption_type']}` ({ta['count']} records)\n")
        lines.append(f"- **Quality gate**: `{ta.get('quality_gate') or 'None'}`")
        lines.append(f"- **Gate detail**: {ta.get('quality_gate_detail', '—')}")
        ids = ta.get("affected_paper_ids", [])
        lines.append(f"- **Affected paper IDs**: {', '.join(f'`{i}`' for i in ids)}")
        lines.append("")

    # --- 6. Stable signals ---
    lines.append("## 6. Stable Signals (No Meaningful Change)\n")
    stable = correlation.get("stable_signals", [])
    changed = correlation.get("changed_signals", [])
    if not mc or not any(v["available"] for v in mc.values()):
        lines.append("_Cannot classify — metric files not yet available._\n")
    elif not stable:
        lines.append("All measured metrics changed significantly. No stable signals identified.\n")
    else:
        lines.append(
            "The following metrics changed by less than ±2 percentage points (|Δ| < 0.02) "
            "and should **not** be cited as evidence of corruption impact:\n"
        )
        for s in stable:
            v = mc.get(s, {})
            lines.append(f"- **`{s}`**: Δ = {v.get('delta'):+.4f} (baseline={_fmt(v.get('baseline'))}, corrupted={_fmt(v.get('corrupted'))})")
        lines.append("")
        if changed:
            lines.append("Metrics with meaningful degradation (|Δ| ≥ 0.02):\n")
            for c in changed:
                v = mc.get(c, {})
                lines.append(f"- **`{c}`**: Δ = {v.get('delta'):+.4f}")
        lines.append("")

    lines.append("## 7. Root Cause Map\n")
    lines.append(
        "| Corruption | Quality gate triggered | Metric degraded | Freshness degraded |\n"
        "|---|---|---|---|\n"
        "| `blank_summary` | `summary_not_blank` FAIL | `retrieval_hit_rate`, `mean_token_f1` ↓ | No |\n"
        "| `inject_noise` | _(none)_ | `mean_token_f1`, `judge_score` ↓ | No |\n"
        "| `drop_latest_record` | `row_count` ↓ | `retrieval_hit_rate` ↓ | Yes (fewer recent records) |\n"
        "| `stale_published_date` | `freshness_age_days` FAIL | _(none directly)_ | Yes |\n"
        "| `truncate_title` | _(none)_ | `retrieval_hit_rate` ↓ (exact lookup fails) | No |\n"
        "| `duplicate_row` | `paper_id_unique` FAIL | `retrieval_hit_rate` ↓ (index diluted) | No |\n"
    )
    lines.append("")

    lines.append("## 8. Conclusion\n")
    lines.append(
        "- Structural corruptions (`blank_summary`, `duplicate_row`) are caught **immediately** by quality gates.\n"
        "- Semantic corruptions (`inject_noise`, `truncate_title`) pass quality gates but show up in evaluation metrics.\n"
        "- Freshness corruption (`stale_published_date`, `drop_latest_record`) is detected by the freshness gate.\n"
        "- Stable signals (if any) show that not every metric is sensitive to every corruption type — "
        "over-attributing a stable metric to a specific corruption is a false conclusion.\n"
        "- The evaluator fallback check ensures silent heuristic-as-success is surfaced, not hidden.\n"
    )

    lines.append("---")
    lines.append("_Generated by data pipeline observability module — Checkpoint 5._\n")

    write_text(Path(report_path), "\n".join(lines))


# ---------------------------------------------------------------------------
# CP6 — 3-state comparison report
# ---------------------------------------------------------------------------

def _recovery_status_label(status: str) -> str:
    return {"full": "FULL", "partial": "PARTIAL", "none": "NOT RECOVERED", "unknown": "N/A"}.get(status, status)


def _gate_status(ok: bool | None) -> str:
    if ok is True:
        return "PASS"
    if ok is False:
        return "FAIL"
    return "—"


def _demo_block(label: str, entry: dict[str, Any] | None) -> list[str]:
    lines: list[str] = []
    if entry is None:
        lines.append(f"_No {label} case available — answers files required._\n")
        return lines
    lines.append(f"**ID**: `{entry.get('id')}`  **Type**: `{entry.get('question_type')}`\n")
    lines.append(f"> **Question**: {entry.get('question')}\n")
    gt = (entry.get("ground_truth_excerpt") or "")
    if gt:
        lines.append(f"> **Ground truth**: {gt}\n")
    lines.append("| State | Token F1 | Judge score | Retrieval hit |")
    lines.append("|---|---|---|---|")
    lines.append(
        f"| Baseline  | {_fmt(entry.get('baseline_token_f1'))} "
        f"| {entry.get('baseline_judge_score') or '—'} | — |"
    )
    lines.append(
        f"| Corrupted | {_fmt(entry.get('corrupted_token_f1'))} "
        f"| {entry.get('corrupted_judge_score') or '—'} "
        f"| {entry.get('corrupted_retrieval_hit')} |"
    )
    lines.append(
        f"| Repaired  | {_fmt(entry.get('repaired_token_f1'))} "
        f"| {entry.get('repaired_judge_score') or '—'} "
        f"| {entry.get('repaired_retrieval_hit')} |"
    )
    lines.append("")
    if entry.get("corrupted_answer_excerpt"):
        lines.append(f"**Corrupted answer**: {entry.get('corrupted_answer_excerpt')}\n")
    if entry.get("repaired_answer_excerpt"):
        lines.append(f"**Repaired answer**: {entry.get('repaired_answer_excerpt')}\n")
    return lines


def generate_cp6_report(
    report_path,
    recovery: dict[str, Any],
) -> None:
    """Checkpoint 6: 3-state comparison report — baseline / corrupted / repaired."""
    lines: list[str] = []
    lines.append("# Checkpoint 6 — Recovery Comparison Report\n")
    lines.append(
        "> So sánh ba trạng thái baseline / corrupted / repaired trên "
        "metric, quality gate, freshness và từng câu trả lời thực tế. "
        "Ghi rõ recovery chưa hoàn toàn và giới hạn kết luận.\n"
    )

    summary = recovery.get("recovery_summary", {})

    # --- 1. Metric 3-state delta table ---
    lines.append("## 1. Metric — 3-State Delta\n")
    mr = recovery.get("metric_recovery", {})
    metrics_available = summary.get("metrics_available", False)
    if not metrics_available:
        lines.append(
            "> _Metric files not found — run `uv run python script/run_corruption_flow.py` "
            "to generate all three metric JSON files. Recovery verdicts show as N/A._\n"
        )
    lines.append("| Metric | Baseline | Corrupted | Repaired | Δ corrupt | Δ repair | Δ recover | Status |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for key, v in mr.items():
        b = _fmt(v.get("baseline"))
        c = _fmt(v.get("corrupted"))
        r = _fmt(v.get("repaired"))
        dc = f"{v['delta_corrupt']:+.4f}" if v.get("delta_corrupt") is not None else "—"
        dr = f"{v['delta_repair']:+.4f}" if v.get("delta_repair") is not None else "—"
        drec = f"{v['delta_recover']:+.4f}" if v.get("delta_recover") is not None else "—"
        status = _recovery_status_label(v.get("recovery_status", "unknown"))
        lines.append(f"| {key} | {b} | {c} | {r} | {dc} | {dr} | {drec} | {status} |")
    lines.append("")

    if not metrics_available:
        lines.append("**Overall metric recovery**: N/A — metric files required.\n")
    else:
        full = summary.get("full_recovered_metrics", [])
        partial = summary.get("partial_recovered_metrics", [])
        none_ = summary.get("not_recovered_metrics", [])
        lines.append(f"- **Fully recovered** (|Δ repair| < 0.02): {', '.join(f'`{m}`' for m in full) or 'none'}")
        lines.append(f"- **Partially recovered** (improved but not baseline): {', '.join(f'`{m}`' for m in partial) or 'none'}")
        lines.append(f"- **Not recovered**: {', '.join(f'`{m}`' for m in none_) or 'none'}")
    lines.append("")

    # --- 2. Quality gate 3-state comparison ---
    lines.append("## 2. Quality Gates — 3-State Comparison\n")
    qr = recovery.get("quality_recovery", [])
    lines.append("| Check | Baseline | Corrupted | Repaired | Gate recovery |")
    lines.append("|---|---|---|---|---|")
    for g in qr:
        b_s = _gate_status(g.get("baseline"))
        c_s = _gate_status(g.get("corrupted"))
        r_s = _gate_status(g.get("repaired"))
        rec = g.get("gate_recovery", "unknown").replace("_", " ").upper()
        lines.append(f"| `{g['check']}` | {b_s} | {c_s} | {r_s} | {rec} |")
    lines.append("")
    lines.append(
        f"**Summary**: "
        f"{summary.get('gate_recovered', '—')} gate(s) recovered · "
        f"{summary.get('gate_still_failing', '—')} still failing · "
        f"{summary.get('gate_stable', '—')} unchanged\n"
    )

    # --- 3. Freshness 3-state ---
    lines.append("## 3. Freshness — 3-State\n")
    fr = recovery.get("freshness_recovery", {})
    lines.append("| State | is_fresh | stale_ratio |")
    lines.append("|---|---|---|")
    lines.append(
        f"| Baseline  | {fr.get('baseline_fresh')} | {_fmt(fr.get('baseline_stale_ratio'))} |"
    )
    lines.append(
        f"| Corrupted | {fr.get('corrupted_fresh')} | {_fmt(fr.get('corrupted_stale_ratio'))} |"
    )
    lines.append(
        f"| Repaired  | {fr.get('repaired_fresh')} | {_fmt(fr.get('repaired_stale_ratio'))} |"
    )
    freshness_ok = fr.get("freshness_recovered", False)
    lines.append(
        f"\n**Freshness recovery**: {'YES — repaired dataset is fresh again.' if freshness_ok else 'NO — still stale after repair.'}\n"
    )

    # --- 4. Per-answer recovery breakdown ---
    lines.append("## 4. Per-Answer Recovery Breakdown\n")
    ans_available = summary.get("answers_available", False)
    label_counts = summary.get("answer_label_counts", {})
    if not ans_available:
        lines.append("_Answer files not available — run the full corruption flow._\n")
    else:
        total = sum(label_counts.values())
        lines.append("| Recovery label | Count | % of questions | Meaning |")
        lines.append("|---|---|---|---|")
        labels_doc = {
            "recovered": "Corrupted broke it, repair fixed it",
            "consistent_hit": "Correct in both corrupted and repaired states",
            "consistent_miss": "Still wrong after repair — unresolved gap",
            "newly_broken": "Repair unexpectedly broke a previously-correct answer",
        }
        for label, doc in labels_doc.items():
            count = label_counts.get(label, 0)
            pct = f"{count / total * 100:.0f}%" if total else "—"
            lines.append(f"| `{label}` | {count} | {pct} | {doc} |")
        lines.append("")

        # Recovery completeness verdict from answers
        recovered_n = label_counts.get("recovered", 0)
        miss_n = label_counts.get("consistent_miss", 0)
        if miss_n == 0:
            lines.append("**Answer-level verdict**: All corrupted misses were recovered.\n")
        else:
            lines.append(
                f"**Answer-level verdict**: {miss_n} question(s) still miss after repair — "
                f"recovery is incomplete at the answer level.\n"
            )

    # --- 5. Representative demo cases ---
    lines.append("## 5. Representative Demo Cases\n")
    demo = recovery.get("demo_cases", {})

    lines.append("### 5a. Hit — Repair Worked (recovered)\n")
    lines.extend(_demo_block("recovered", demo.get("demo_hit")))

    lines.append("### 5b. Miss — Still Broken After Repair (consistent_miss)\n")
    lines.extend(_demo_block("consistent_miss", demo.get("demo_miss")))

    lines.append("### 5c. Stable — Always Correct (consistent_hit, baseline held)\n")
    lines.extend(_demo_block("stable", demo.get("demo_stable")))

    # --- 6. Recovery completeness + limitations ---
    lines.append("## 6. Recovery Completeness & Limitations\n")

    # Overall verdict
    q_full = summary.get("gate_still_failing", 0) == 0
    f_full = fr.get("freshness_recovered", False) or (fr.get("repaired_fresh") is True)
    m_full = metrics_available and not summary.get("partial_recovered_metrics") and not summary.get("not_recovered_metrics")

    lines.append("| Dimension | Recovery verdict |")
    lines.append("|---|---|")
    lines.append(f"| Quality gates | {'COMPLETE' if q_full else 'INCOMPLETE'} |")
    lines.append(f"| Freshness | {'COMPLETE' if f_full else 'INCOMPLETE'} |")
    lines.append(f"| Evaluation metrics | {'COMPLETE' if m_full else 'INCOMPLETE (or N/A)'} |")
    ans_label_ok = label_counts.get("consistent_miss", 0) == 0 if ans_available else None
    lines.append(f"| Per-answer retrieval | {'COMPLETE' if ans_label_ok else ('INCOMPLETE' if ans_label_ok is False else 'N/A')} |")
    lines.append("")

    limits = summary.get("limitations", [])
    if limits:
        lines.append("### Known limitations\n")
        for lim in limits:
            lines.append(f"- {lim}")
        lines.append("")
    else:
        lines.append("No unresolved limitations detected with available data.\n")

    lines.append("### What this report cannot conclude\n")
    lines.append(
        "- Recovery of **semantic quality** (answer correctness) cannot be confirmed from quality gates alone — "
        "only evaluation metrics and answer comparison can show this.\n"
        "- If the repaired source data itself contains undiscovered issues, "
        "quality gates will pass but evaluation metrics may still be below baseline.\n"
        "- `consistent_miss` cases may reflect **test-set questions that are inherently hard**, "
        "not repair failures — without a larger test set we cannot distinguish the two.\n"
        "- Metric improvement from corrupted to repaired does **not** prove causation — "
        "if the raw source data changed between runs, the improvement may reflect new data, not repair.\n"
    )

    lines.append("---")
    lines.append("_Generated by data pipeline observability module — Checkpoint 6._\n")

    write_text(Path(report_path), "\n".join(lines))
