"""Checkpoint 5 — Correlation analysis runner.

Loads pre-computed artifacts (corruption log, quality reports, freshness reports,
and optionally baseline/corrupted metric/answer files) then:
  1. Runs correlate_corruption_signals() to link each corruption type to its
     quality gate, metric delta, and worst-degraded individual case.
  2. Saves the structured analysis to data/results/cp5_analysis.json.
  3. Generates the full Markdown report to data/reports/cp5_report.md.

No LLM credentials required — works on existing data files.
Metric comparison and worst-case evidence are included automatically when the
answer and metric JSON files exist (generated by run_corruption_flow.py).

Run:
    uv run python script/run_cp5_analysis.py
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Ensure this project's src is resolved first so Role 4 modules take precedence
# over any sibling workspace that may be on the editable-install path.
_this_src = Path(__file__).resolve().parents[1] / "src"
if str(_this_src) not in sys.path:
    sys.path.insert(0, str(_this_src))

from core.config import load_settings
from core.utils import read_json, write_json
from observability.correlation import correlate_corruption_signals
from observability.reporting import generate_cp5_report

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)


def _load_optional(path: Path, default):
    if path.exists():
        log.info("  Loaded: %s", path)
        return read_json(path)
    log.warning("  Not found (optional): %s — using default.", path)
    return default


def main() -> None:
    log.info("=== Checkpoint 5: Corruption Signal Correlation Analysis ===")
    settings = load_settings()
    paths = settings.paths

    # Required files
    if not paths.corruption_log.exists():
        raise FileNotFoundError(
            f"Corruption log not found at {paths.corruption_log}. "
            "Run run_corruption_flow.py first."
        )
    if not (paths.quality_dir / "corrupted_quality.json").exists():
        raise FileNotFoundError(
            f"Corrupted quality report not found. Run run_corruption_flow.py first."
        )

    log.info("[1] Loading corruption log: %s", paths.corruption_log)
    corruption_log = read_json(paths.corruption_log)

    log.info("[2] Loading quality & freshness reports...")
    corrupted_quality = read_json(paths.quality_dir / "corrupted_quality.json")
    corrupted_freshness = read_json(paths.quality_dir / "corrupted_freshness.json")

    log.info("[3] Loading metrics & answers (optional — enriches analysis)...")
    baseline_metrics = _load_optional(paths.baseline_metrics, {})
    corrupted_metrics = _load_optional(paths.corrupted_metrics, {})
    baseline_answers = _load_optional(paths.baseline_answers, [])
    corrupted_answers = _load_optional(paths.corrupted_answers, [])

    log.info("[4] Running correlation analysis...")
    result = correlate_corruption_signals(
        corruption_log=corruption_log,
        baseline_metrics=baseline_metrics,
        corrupted_metrics=corrupted_metrics,
        corrupted_quality=corrupted_quality,
        corrupted_freshness=corrupted_freshness,
        corrupted_answers=corrupted_answers,
        baseline_answers=baseline_answers,
    )

    # Save structured analysis
    analysis_path = paths.quality_dir.parent / "results" / "cp5_analysis.json"
    write_json(analysis_path, result)
    log.info("[5] Saved analysis JSON: %s", analysis_path)

    # Generate Markdown report
    report_path = paths.baseline_report.parent / "cp5_report.md"
    generate_cp5_report(
        report_path=report_path,
        correlation=result,
        corrupted_quality=corrupted_quality,
        corrupted_freshness=corrupted_freshness,
    )
    log.info("[6] Saved Markdown report: %s", report_path)

    # Print summary
    summary = result.get("summary", {})
    log.info("=== Summary ===")
    log.info(
        "  Corruptions: %d across %d types",
        summary.get("total_corruptions", 0),
        len(summary.get("corruption_types", [])),
    )
    log.info(
        "  Quality gates: %d/%d failed",
        summary.get("quality_gates_failed", 0),
        summary.get("quality_gates_total", 0),
    )
    log.info("  Changed signals: %s", result.get("changed_signals") or "none (metrics not available)")
    log.info("  Stable signals:  %s", result.get("stable_signals") or "none (metrics not available)")
    fb = result.get("evaluator_fallback_count", 0)
    if fb:
        log.warning("  FALLBACK JUDGE DETECTED: %d answer(s) used heuristic fallback!", fb)
    else:
        log.info("  Evaluator fallback: none detected (LLM judge ran cleanly or answers not available)")
    wc = result.get("worst_degraded_case")
    if wc:
        log.info(
            "  Worst case: id=%s  token_f1 delta=%.4f",
            wc.get("id"),
            wc.get("token_f1_delta", 0),
        )
    log.info("=== Checkpoint 5 COMPLETE ===")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        log.error("CP5 analysis failed: %s", exc)
        raise SystemExit(1)
